name: Update README with Date and Day

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (UTC)
  workflow_dispatch:  # Allows the workflow to be manually triggered

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Get the current date and day
      - name: Get current date and day
        id: date
        run: |
          # Get current date and day (in UTC)
          DATE=$(date -u "+%Y-%m-%d")
          DAY=$(date -u "+%A")
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "DAY=$DAY" >> $GITHUB_ENV

      # Step 3: Update README.md
      - name: Update README.md
        run: |
          # Replace placeholders in README with the actual date and day
          sed -i "s/{DATE}/${DATE}/g" README.md
          sed -i "s/{DAY}/${DAY}/g" README.md
          
          # Commit changes to README.md if there are any updates
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git add README.md
          git commit -m "Update date and day in README" || echo "No changes"
          git push

